# Generated by Django 4.2.11 on 2024-04-04 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_room_options_room_participants"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="messages",
            options={"ordering": ["-updated", "-created"]},
        ),
    ]
